services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=prod


  # frontend:
  #   image: frontend:latest
  #   build:
  #     context: ./frontend 
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:80"
  #   depends_on:
  #     - backend

volumes:
  mongodb_data: