# networks:
#   app-network:
#     name: backend_app-network
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=prod

    # networks:
    #   - app-network

volumes:
  mongodb_data: